name: Publish Firefox Extension

on:
  push:
    branches:
      - release

jobs:
  publish-firefox:
    uses: ./.github/workflows/common.yml
    with:
      build_command: npm run build:firefox
      dist_folder: ./dist/firefox
      zip_name: firefox-extension

  publish:
    runs-on: ubuntu-latest
    needs: publish-firefox

    steps:
    - name: Sign and Publish to Firefox Add-ons Store
      env:
        AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
        AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
      run: |
        npx web-ext sign --source-dir ./dist/firefox \
                         --api-key $AMO_API_KEY \
                         --api-secret $AMO_API_SECRET \
                         --channel listed
