name: Publish Chrome Extension

on:
  push:
    branches:
      - release

jobs:
  publish-chrome:
    uses: ./.github/workflows/common.yml
    with:
      build_command: npm run build:chrome
      dist_folder: ./dist/chrome
      zip_name: chrome-extension

  publish:
    runs-on: ubuntu-latest
    needs: publish-chrome

    steps:
    - name: Upload to Chrome Web Store
      env:
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
      run: |
        npx webstore upload --source chrome-extension-${{ needs.publish-chrome.outputs.VERSION }}.zip \
                            --extension-id $EXTENSION_ID \
                            --client-id $CLIENT_ID \
                            --client-secret $CLIENT_SECRET \
                            --refresh-token $REFRESH_TOKEN
